ruby:
  enabled: true
  # config_file: config/.rubocop.yml
  
coffee_script:
  enabled: true
  # config_file: config/.coffeelint.json
  
# java_script:
#   enabled: true
#   config_file: config/.jshint.json